<?php if($this->getOrder()->getPayment()->getMethod()!='gwap_boleto'): ?>
<ul>
    <li>
        <?php echo Mage::getStoreConfig('payment/gwap_cc/nautorizado'); ?>
    </li>
</ul>
<?php endif; ?>
<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
