<?php if ($this->isActive()): ?>
        <div class="advancedinstallments-view">
        <?php ?>
                <p class="advancedinstallments-title"><?php echo $this->__('Opções de parcelamento:'); ?></p>
                <div class="advancedinstallments-parcelas-view">
                <?php foreach($this->getInstallments() as $installment): ?>
                        <?php echo $installment->getValue().' x '. $installment->getInstallment() . ' ' . $installment->getMessage(); ?>
                        <br />
                <?php endforeach; ?>
                </div>
        <?php ?>
        </div>
<?php endif; ?>
